# hyprlock — 锁屏配置

background {
    monitor =
    path = /usr/share/backgrounds/lain.jpg
    blur_passes = 3
    blur_size = 7
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(30, 30, 46, 0.8)
    font_color = rgb(200, 200, 220)
    fade_on_empty = false
    placeholder_text = Password...
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 220, 1)
    font_size = 70
    position = 0, 80
    halign = center
    valign = center
}
