# zimrc.zsh
zmodule environment
zmodule input
zmodule termtitle
zmodule utility
zmodule completion
zmodule zsh-users/zsh-completions
zmodule zsh-users/zsh-autosuggestions
zmodule zsh-users/zsh-history-substring-search
zmodule zdharma-continuum/fast-syntax-highlighting
zmodule hlissner/zsh-autopair
